name: Process README Placeholders

on:
  push:
    paths:
      - "package_info.py"
      - "setup.py"
      - "readme.md"
      - "readme.template.md"
      - "process_readme.py"

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Get GitHub Username
        id: get-username
        run: echo "GITHUB_USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Generate README
        env:
          GITHUB_USERNAME: ${{ env.GITHUB_USERNAME }}
        run: |
          python process_readme.py

      - name: Commit updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add readme.md
          git commit -m "Update README with metadata" || echo "No changes to commit"
          git push
